---
- name: install
  apt: name={{ item }} state=present
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: configure my.cnf
  template:
    src=my.cnf.j2
    dest=/etc/mysql/my.cnf
  notify:
      - restart mysql

- name: wait for mysql
  wait_for: port={{mariadb.config.mysqld.port}}

- name: change default user to {{ mariadb.username }} / {{ mariadb.password }}
  mysql_user: name={{ mariadb.username }} password={{ mariadb.password }} check_implicit_admin=true

- name: copy .my.cnf file for user root
  template:
    src=user-my.cnf.j2
    dest=/root/.my.cnf
    owner=root
    group=root
    mode=0600

- name: copy .my.cnf for user vagrant
  template:
    src=user-my.cnf.j2
    dest=/home/vagrant/.my.cnf
    owner=vagrant
    group=vagrant
    mode=0600
