---
- name: add key
  apt_key: keyserver=keyserver.ubuntu.com id=4F4EA0AAE5267A6C state=present

- name: app repository
  apt_repository: repo='deb http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu trusty main' state=present

- name: app src repository
  apt_repository: repo='deb-src http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu trusty main' state=present

- name: install core, common, cli, fpm
  apt: name={{ item }} state=present
  with_items:
    - php5
    - php5-common
    - php5-cli
    - php5-fpm
    - php5-apcu
  notify:
    - restart php56-fpm

- name: install memcached
  apt: name={{ item }} state=present
  with_items:
    - php5-memcached
  notify:
    - restart php56-fpm
  when: role.memcached

- name: install mongo
  apt: name={{ item }} state=present
  with_items:
    - php5-mongo
  notify:
    - restart php56-fpm
  when: role.mongodb

- name: install mysqlnd
  apt: name={{ item }} state=present
  with_items:
    - php5-mysqlnd
  notify:
    - restart php56-fpm
  when: role.mariadb

- name: install pgsql
  apt: name={{ item }} state=present
  with_items:
    - php5-pgsql
  notify:
    - restart php56-fpm
  when: role.postgresql

- name: install redis
  apt: name={{ item }} state=present
  with_items:
    - php5-redis
  notify:
    - restart php56-fpm
  when: role.redis

- name: install sybase
  apt: name={{ item }} state=present
  with_items:
    - php5-sybase
  notify:
    - restart php56-fpm
  when: role.freetds

- name: install modules
  apt: name="php5-{{ php.modules|join(',php5-') }}" state=present
  notify:
    - restart php56-fpm

- name: configure cli php.ini
  template:
    src=cli.php.ini.j2
    dest=/etc/php5/cli/php.ini

- name: configure fpm php.ini
  template:
    src=fpm.php.ini.j2
    dest=/etc/php5/fpm/php.ini
  notify:
    - restart php56-fpm

- name: fpm config
  template:
    src=php-fpm.conf.j2
    dest=/etc/php5/fpm/php-fpm.conf
  notify:
    - restart php56-fpm
