---
### apt
- name: apt | upgrade
  apt: update_cache=yes upgrade=full

- name: apt | install packages
  apt: name={{ item }} state=present
  with_items: "{{ general.packages}} "

### locale

- name: locale | install
  apt: name={{ item }} state=present
  with_items:
    - locales

- name: locale | Generate {{ general.config.locale }}
  command: /usr/sbin/locale-gen {{ general.config.locale }}

- name: locale | Set locale to {{ general.config.locale }}
  command: /usr/sbin/update-locale LANG={{ general.config.locale }} LC_ALL={{ general.config.locale }}

### timezone

- name: timezone | Set /etc/localtime to {{ general.config.timezone }}
  command: /bin/cp /usr/share/zoneinfo/{{ general.config.timezone }} /etc/localtime

- name: timezone | Update tzdata
  command: dpkg-reconfigure --frontend noninteractive tzdata

### keymap

- name: keymap | copy keyboard config
  template:
    src=keyboard.j2
    dest=/etc/default/keyboard
    owner=root
    group=root

- name: keymap | setupcon
  command: /bin/setupcon

### grub

- name: grub | fix boot hidden timeout
  lineinfile:
    dest=/etc/default/grub
    line='#GRUB_HIDDEN_TIMEOUT=0'
    regexp='^(|#)GRUB_HIDDEN_TIMEOUT\='
    state=present
  register: fixbootparameter

- name: grub | fix boot hidden timeput quiet
  lineinfile:
    dest=/etc/default/grub
    line='GRUB_HIDDEN_TIMEOUT_QUIET=true'
    regexp='^GRUB_HIDDEN_TIMEOUT_QUIET\='
    state=present
  register: fixbootparameter

- name: grub | fix boot timeout
  lineinfile:
    dest=/etc/default/grub
    line='GRUB_TIMEOUT=3'
    regexp='^GRUB_TIMEOUT\='
    state=present
  register: fixbootparameter

- name: grub | update
  command: /usr/sbin/update-grub
  when: fixbootparameter.changed

### disable-transparent-hugepages

- name: disable-transparent-hugepages | add init script disable-transparent-hugepages
  copy:
    src=disable-transparent-hugepages
    dest=/etc/init.d/disable-transparent-hugepages
    owner=root
    group=root
    mode=755

- name: disable-transparent-hugepages | register init script disable-transparent-hugepages
  command: /usr/sbin/update-rc.d disable-transparent-hugepages defaults

### swap

- name: additional_swap | check swap image exists
  stat: path=/var/swap.1
  register: additional_swap_file_exists

- name: additional_swap | image
  command: /bin/dd if=/dev/zero of=/var/swap.1 bs=1M count={{ additional_swap }}
  when: additional_swap != 0 and additional_swap_file_exists.stat.exists == False

- name: additional_swap | mkswap
  command: /sbin/mkswap /var/swap.1
  when: additional_swap != 0 and additional_swap_file_exists.stat.exists == False

- name: additional_swap | swapon
  command: /sbin/swapon /var/swap.1
  when: additional_swap != 0
  ignore_errors: yes

### python
- name: python | add key for ppa python repository
  apt_key: keyserver=keyserver.ubuntu.com id=DB82666C state=present

- name: python | Add ppa python repository
  apt_repository: repo='deb http://ppa.launchpad.net/fkrull/deadsnakes-python2.7/ubuntu trusty main' state=present update_cache=yes

- name: python | ensure python2.7 tatest is installed
  apt:
    pkg: python2.7
    state: latest
    install_recommends: no
