---
- name: add apt key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

- name: app repository
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main' state=present

- name: install
  apt: name={{ item }} state=present
  with_items:
    - postgresql-9.4
    - python-psycopg2

- name: configure postgresql.conf
  template:
    src=postgresql.conf.j2
    dest=/etc/postgresql/9.4/main/postgresql.conf
  notify:
      - restart postgresql

- name: wait for postgresql
  wait_for: port={{postgresql.config.port}}

- name: change default user to {{ postgresql.username }} / {{ postgresql.password }}
  become_user: postgres
  postgresql_user: name={{ postgresql.username }} password={{ postgresql.password }} role_attr_flags=SUPERUSER

- name: copy .pgpass for postgres
  template:
    src=user-pgpass.j2
    dest=/var/lib/postgresql/.pgpass
    owner=postgres
    group=postgres
    mode=0600
